# Generated by Django 5.2.1 on 2025-12-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_name'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetIncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='budget.budget')),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.incometype')),
            ],
        ),
    ]
