# Generated by Django 5.2.1 on 2025-07-15 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_household_customuser_household_householdmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household', to='users.household'),
        ),
    ]
