# Generated by Django 5.2.1 on 2025-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('gap_open_price', models.FloatField()),
                ('gap_open_percentage', models.FloatField()),
            ],
        ),
    ]
