# Generated by Django 5.2.1 on 2025-07-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydata',
            old_name='close_price',
            new_name='previous_close_price',
        ),
    ]
