# Generated by Django 5.2.1 on 2025-07-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_close_price_dailydata_previous_close_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='isin_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
