# Generated by Django 5.2.1 on 2025-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_dailydata_isin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
