# Generated by Django 5.2.1 on 2025-07-31 12:33

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_dailydata_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('time_zone', models.CharField(choices=[('Europe/Sofia', 'Europe/Sofia'), ('Europe/Berlin', 'Europe/Berlin'), ('Asia/Hong_Kong', 'Asia/Hong_Kong'), ('America/New_York', 'America/New_York'), ('Asia/Tokyo', 'Asia/Tokyo'), ('UTC', 'UTC')], default='UTC', max_length=50)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('open_days', multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default=['MON', 'TUE', 'WED', 'THU', 'FRI'], max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='finance.market')),
            ],
            options={
                'unique_together': {('market', 'date')},
            },
        ),
    ]
