# Generated by Django 5.2.1 on 2025-07-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_market_marketholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDataInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('open_price', models.FloatField()),
                ('previous_close_price', models.FloatField()),
                ('gap_open_price', models.FloatField()),
                ('gap_open_percentage', models.FloatField()),
                ('isin_number', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
