# Generated by Django 5.2.1 on 2025-08-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_symbolsmapping_official_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentalsdata',
            name='symbol_yahoo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
