# Generated by Django 5.2.1 on 2025-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_fundamentalsdata_symbol_yahoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='base_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='margin_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailydatainvest',
            name='base_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dailydatainvest',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailydatainvest',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailydatainvest',
            name='part_from_index',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
