# Generated by Django 5.2.1 on 2025-08-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_dailydata_base_currency_dailydata_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='long_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
