# Generated by Django 5.2.1 on 2025-08-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_instrumenttypesinvest_instrumenttypestrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ratio', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
