# Generated by Django 5.2.1 on 2025-09-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_portfoliotransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotransaction',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
