# Generated by Django 5.2.1 on 2025-05-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
