# Generated by Django 5.2.1 on 2025-07-13 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_recipetimescooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetimescooked',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
