# Generated by Django 5.2.1 on 2025-07-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_recipetimescooked_date'),
        ('users', '0005_alter_customuser_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdRecipeTimesCooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_recipe_times_cooked', to='users.household')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_recipe_times_cooked', to='cooking.recipe')),
            ],
        ),
    ]
