# Generated by Django 5.2.1 on 2025-12-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_userfavouriterecipe_userfavoriterecipedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavouriterecipe',
            name='recipes',
            field=models.ManyToManyField(related_name='in_favourite_groups', through='cooking.UserFavoriteRecipeData', to='cooking.recipe'),
        ),
        migrations.AlterField(
            model_name='userfavoriterecipedata',
            name='favourite_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cooking.userfavouriterecipe'),
        ),
    ]
