# Generated by Django 5.2.1 on 2025-12-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_userfavouriterecipe_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
    ]
