# Generated by Django 5.2.1 on 2025-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_category_name_alter_thread_title_threadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
