# Generated by Django 5.2.1 on 2025-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_threadrequest_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadrequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='threadrequest',
            name='staus',
            field=models.CharField(choices=[('pending', 'Изчкаваща'), ('approved', 'Одобрена'), ('rejected', 'Отхвърлена')], default='pending', max_length=10),
        ),
    ]
