# Generated by Django 5.2.1 on 2025-07-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_threadrequest_approved_threadrequest_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadrequest',
            old_name='staus',
            new_name='status',
        ),
    ]
