# Generated by Django 5.2.1 on 2025-07-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Нисък', 'Нисък'), ('Нормален', 'Нормален'), ('Висок', 'Висок')], default='Нормален', max_length=10),
        ),
    ]
