# Generated by Django 5.2.1 on 2025-05-22 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='UserProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direct_planning', models.BooleanField(default=False)),
                ('daily_consumption', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
