# Generated by Django 5.2.1 on 2025-05-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryproduct_category_userproductcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='category',
            field=models.IntegerField(default=None, max_length=100),
        ),
    ]
