# Generated by Django 5.2.1 on 2025-05-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='category',
        ),
    ]
