# Generated by Django 5.2.1 on 2025-05-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryproduct_category_inventoryproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='name',
        ),
    ]
