# Generated by Django 5.2.1 on 2025-07-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_userproductcategory_name'),
        ('shopping', '0013_remove_basketitem_basket_remove_basketitem_product_and_more'),
        ('users', '0005_alter_customuser_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdInventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_inventory_category', to='shopping.productcategory')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.household')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_inventory_product', to='shopping.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
