# Generated by Django 5.2.1 on 2025-07-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_householdinventoryproduct'),
        ('shopping', '0013_remove_basketitem_basket_remove_basketitem_product_and_more'),
        ('users', '0005_alter_customuser_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_planning', models.BooleanField(default=False)),
                ('daily_consumption', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.household')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_product_category', to='shopping.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
