# Generated by Django 5.2.1 on 2025-07-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_householdproductcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdproductcategory',
            name='inventory_related',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userproductcategory',
            name='inventory_related',
            field=models.BooleanField(default=True),
        ),
    ]
