# Generated by Django 5.2.1 on 2025-07-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_householdproductcategory_inventory_related_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdproductcategory',
            name='inventory_related',
        ),
        migrations.RemoveField(
            model_name='userproductcategory',
            name='inventory_related',
        ),
        migrations.AddField(
            model_name='householdinventoryproduct',
            name='inventory_related',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='inventory_related',
            field=models.BooleanField(default=True),
        ),
    ]
