# Generated by Django 5.2.1 on 2025-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=7, max_digits=12)),
                ('date_extracted', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency', 'date_extracted')},
            },
        ),
    ]
