# Generated by Django 5.2.1 on 2025-08-27 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_userbook_shared_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
