# Generated by Django 5.2.1 on 2025-08-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_userbook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
