# Generated by Django 5.2.1 on 2025-08-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_userbook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
