# Generated by Django 5.2.1 on 2026-03-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('BGN', 'лв.'), ('USD', 'US Dollar')], default='BGN', max_length=3),
        ),
    ]
