# Generated by Django 5.2.1 on 2025-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_recipeshoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeshoppinglist',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
