# Generated by Django 5.2.1 on 2025-07-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_recipeshoppinglist_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='sent',
            new_name='executed',
        ),
    ]
