# Generated by Django 5.2.1 on 2025-07-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_rename_sent_shoppinglist_executed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeshoppinglist',
            old_name='sent',
            new_name='executed',
        ),
    ]
