# Generated by Django 5.2.1 on 2025-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_alter_product_name_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='utility_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
