# Generated by Django 5.2.1 on 2025-07-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_shop_utility_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
