# Generated by Django 5.2.1 on 2025-07-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_remove_basketitem_basket_remove_basketitem_product_and_more'),
        ('users', '0005_alter_customuser_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdRecipeShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.BooleanField(default=False)),
                ('items', models.JSONField(default=list)),
                ('recipe_name', models.CharField(max_length=150)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.household')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseholdShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.BooleanField(default=False)),
                ('items', models.JSONField(default=list)),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.household')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
