# Generated by Django 5.2.1 on 2025-07-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_householdrecipeshoppinglist_householdshoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingproduct',
            name='not_for_household',
            field=models.BooleanField(default=False),
        ),
    ]
