# Generated by Django 5.2.1 on 2025-07-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_shoppingproduct_not_for_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_for_cooking',
            field=models.BooleanField(default=False),
        ),
    ]
