# Generated by Django 5.2.1 on 2025-07-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_shopping_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='currency',
            field=models.CharField(choices=[('BGN', 'лв.'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='BGN', max_length=3),
        ),
    ]
