# Generated by Django 5.2.1 on 2026-03-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_alter_shopping_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('BGN', 'лв.'), ('USD', 'US Dollar')], default='BGN', max_length=3),
        ),
        migrations.AddIndex(
            model_name='shoppingproduct',
            index=models.Index(fields=['product'], name='shopping_sh_product_7fb9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingproduct',
            index=models.Index(fields=['shopping'], name='shopping_sh_shoppin_f7efa5_idx'),
        ),
    ]
